# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LayoutPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LayoutPractice
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'SnapKit'

end
